[package]
name = "rust-chess-bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = { version = "1.0.48", features = [] }
num-traits = "0.2.17"
leb128 = "0.2.1"
bitintr = "0.3.0"
unroll = "0.1.5"
#jemallocator = "0.5.4"
